set(sources ${sources}
	src/Console.cpp
	src/Graphics.cpp
	src/Hooks.cpp
	src/Input.cpp
	src/PCH.cpp
	src/Papyrus.cpp
	src/PhotoMode/Hotkeys.cpp
	src/PhotoMode/Manager.cpp
	src/PhotoMode/Tabs/Camera.cpp
	src/PhotoMode/Tabs/CameraPositions.cpp
	src/PhotoMode/Tabs/Character.cpp
	src/PhotoMode/Tabs/Filters.cpp
	src/PhotoMode/Tabs/Overlays.cpp
	src/PhotoMode/Tabs/Time.cpp
	src/Screenshots/LoadScreen.cpp
	src/Screenshots/Manager.cpp
	src/Settings.cpp
	src/main.cpp
)
